- include/command-line-processing.php
The behavior that an image operator will be applied to each images in an image sequence is not documented. However, that is problematic for some operations such as resizing optimized GIF and therefore should be noted.
> Note that an image operator will be applied to each images in a sequence

- include/command-line-options.php
Describe the new command line option `heic:preserse-orientation` introduced in https://github.com/ImageMagick/ImageMagick/pull/1233
> Describe 'heic:preserve-orientation'

- include/command-line-options.php
Fix description of command line option 'heic:preserve-orientation'  introduced in https://github.com/ImageMagick/ImageMagick/pull/1233
> Fix  'heic:preserve-orientation' 

- include/formats.php
I spend a good deal of time today trying to get right alignment to work with pango; I used `-gravity` but I had strange results since my emojis were rotated (see below).
Now that I saw https://github.com/ImageMagick/ImageMagick/issues/1488 I wanted to help the rest of the world see this :heart: 
I am considering updating the [Pango part of 'Text to Image Handling' in the examples](https://github.com/ImageMagick/usage-markdown/blob/a933c922d882bbfde0341f7636a4720f89f551d7/text/index.md#pango-notes-and-problems-pango_notes), however that repo has been updated last in 2016. Do you have an idea if a pull request would even be considered if I made one today? or is there a better place to add an example for ImageMagick v7?
<details>
`convert -gravity West -background '#CCCCCC' pango:'line …
> Mention -define pango:align

- include/advanced-unix-installation.php
I deleted the word **environment** which was unexpectedly repeated.
> Fix word repetition in advanced-unix-installation.php

- include/command-line-options.php
I deleted the word **the** which was unexpectedly repeated.
> Fix word repetition in alpha CLI option - Extract argument type description

- include/command-line-options.php
I deleted the word **also** which was unexpectedly repeated.
> Fix word repetition in dither command line option description

- include/command-line-options.php
I deleted the word **segment** which was unexpectedly repeated.
> Fix word repetition in draw command line option - arc description

- include/command-line-options.php
I deleted the word **value** which was unexpectedly repeated.
> Fix word repetition in level-colors command line option description

- include/escape.php
I deleted the word **added** which was unexpectedly repeated.
> Fix word repetition in escape properties section

- Magick++/Enumerations.html
I deleted the word **and** which was unexpectedly repeated.
> Fix word repetition in Enumerations.html CompositeOperator OverCompositeOp

- Magick++/Image++.html
I deleted the word **is** which was unexpectedly repeated.
> Fix word repetition in Image++ display method description

- Magick++/TypeMetric.html
I deleted the word **the** which was unexpectedly repeated.
> Fix word repetition in TypeMetric.html descent method description

- include/formats.php
Just adding info for FLIF to the formats page. It's been included with ImageMagick for a few years, but wasn't in the list. I left the "Notes" column blank, but someone more knowledgeable might want to add a note about the needed FLIF dependencies and versioning there.
> Added info for FLIF

- include/identify.php
The example for identify's default output had no labels identifying the various fields.
Related: ImageMagick/ImageMagick#1504
> Add default output description for identify

- include/download.php
You can't use custom options with Homebrew anymore.
Users that need a custom build must compile the project manually.
> Update macOS installation instructions

- include/formats.php
The link was to a now-outdated committee draft of the specification, which is quite far from the final specification.
> Remove link to outdated JXL spec 

- include/command-line-options.php
Was reading the docs, and I think I ran into a typo?
At least I assume this was meant to say "may be **deprecated** in the future.", not "depreciated".
> Fixed Typo in command-line-options.php

- include/command-line-options.php
I'm aware that the beta has expanded capabilities for handling ratios, but this at least is a start and explains the current functionality.
> add use of ratio to -extent

- include/color-thresholding.php
- include/command-line-options.php
For https://imagemagick.org/script/command-line-options.php#family
There are a few weird characters, and the links go to https://imagemagick.org/script/command-line-options.html#pointsize which is a broken link, rather than https://imagemagick.org/script/command-line-options.php#pointsize
> Fix weird char and bad link,

- include/defines.php
Added defaults and valid values for heic parameters.
Sources:
- heic:chroma
- [default](https://github.com/strukturag/libheif/blob/1d36c10ade9b2acfc2dcc4ca8b6176a9789c902c/libheif/heif_encoder_aom.cc#L244)
- [valid values](https://github.com/strukturag/libheif/blob/1d36c10ade9b2acfc2dcc4ca8b6176a9789c902c/libheif/heif_encoder_aom.cc#L136-L138)
- heic:speed
- [default](https://github.com/strukturag/libheif/blob/1d36c10ade9b2acfc2dcc4ca8b6176a9789c902c/libheif/heif_encoder_aom.cc#L191)
- [valid values](https://github.com/strukturag/libheif/blob/1d36c10ade9b2acfc2dcc4ca8b6176a9789c902c/libheif/heif_encoder_aom.cc#L194-L201)
> Update heic -define doc

- include/command-line-options.php
An incredibly minor typo fix. Reading on the web, I happened to notice an unclosed quote around the "Sync" in "`'Sync flag`", one of the times it was mentioned. (Well, once I figured out that it meant `'Sync' flag`.)
> command-line-options: add missing close-quote

- Magick++/Enumerations.html
- Magick++/Image++.html
According the links below, the storage type and pixel map need an update for the Image constructor:
https://github.com/ImageMagick/ImageMagick/blob/2a69677d2e41292f23938073c3a2b78380f7d5ed/MagickCore/constitute.c#L201
https://github.com/ImageMagick/ImageMagick/blob/2a69677d2e41292f23938073c3a2b78380f7d5ed/MagickCore/pixel.c#L4197
https://github.com/ImageMagick/ImageMagick/blob/2a69677d2e41292f23938073c3a2b78380f7d5ed/MagickCore/pixel.h#L154
> Fix image constructor documentation

- include/webp.php
~`segment`~ ➝ `segments` as per https://github.com/ImageMagick/ImageMagick/blob/f86cbbd/coders/webp.c#L1188
> Fix `webp.php` `segment` typo
